directory: "~/Beets"
library: "~/Beets/library.db"
plugins: convert embedart fetchart inline missing
import:
    move: yes
paths:
    default: $albumartist/$albumartist - $album ($year) [$format%if{$bitdepth, - $bitdepth} - $samplerate]/$track. $title
embedart:
    maxwidth: 700
    ifempty: yes
fetchart:
    high_resolution: yes
convert:
    format: opus
    aac:
        command: ffmpeg -i $source -y -vn -acodec aac_at -aq 1 $dest
        extension: m4a
    copy_album_art: yes